- name: Install Apache on GCP VM
  hosts: 10.246.10.61
  become: true  #run as root
  gather_facts: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Start Apache
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

