---
- name: Install Terraform on a VM
  hosts: terraform_vm
  become: yes
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name:
          - wget
          - unzip
        state: present
        update_cache: yes

    - name: Download Terraform binary
      get_url:
        url: "https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip"
        dest: "/tmp/terraform.zip"

    - name: Unzip Terraform binary
      unarchive:
        src: "/tmp/terraform.zip"
        dest: "/usr/local/bin/"
        remote_src: yes

    - name: Ensure Terraform binary is executable
      file:
        path: "/usr/local/bin/terraform"
        mode: '0755'

    - name: Verify Terraform installation
      command: terraform version
      register: terraform_version
      changed_when: false

    - name: Display Terraform version
      debug:
        msg: "Terraform version: {{ terraform_version.stdout }}"
