---
- name: Fully Remove Apache from RHEL 9
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Stop Apache service if running
      ansible.builtin.service:
        name: httpd
        state: stopped
        enabled: no

    - name: Remove Apache and related packages
      ansible.builtin.shell: |
        dnf remove -y httpd* mod_ssl* apr* apr-util*
      register: remove_apache
    - debug:
        var: remove_apache.stdout

    - name: Remove residual configuration files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/httpd
        - /var/www
        - /var/log/httpd
        - /usr/lib64/httpd
        - /run/httpd

    - name: Clean up package cache
      ansible.builtin.shell: |
        dnf clean all

    - name: Verify Apache and dependencies are uninstalled
      ansible.builtin.shell: |
        rpm -qa | grep httpd || echo "Apache and dependencies are removed"
      register: apache_verification
    - debug:
        var: apache_verification.stdout
